version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-llama
    container_name: open-llama-dev
    command: jupyter lab --allow-root --ip="0.0.0.0" --port="8889"
    ports:
      - "8889:8889"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - "./app:/app"
      - "./models:/models"
      - "./notebooks:/workspace"
