version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-llama
    container_name: open-llama-dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - "./app:/app"
      - "./models:/models"
